<?php 
$tmpCfg = Mage::registry('tmpCfg');
$theme=$this->helper('unicase');
$Cfg = $tmpCfg['set']['product_info'];
$tabs=$Cfg['productinfo_tabs_enable'];
$tabstyle=($Cfg['product_tab_style']=='verticle') ? 'pi-ver-tabs' : 'pi-hor-tabs';
?>
<?php if($tabs && ($get_tabs = $this->getTabs())): ?>
<div class="product-tabs inner-bottom-xs wow fadeInUp <?php echo $tabstyle; ?>">
	<div class="row">
		<div class="product-collateral toggle-content tabs col-sm-12">
			<dl id="collateral-tabs" class="collateral-tabs">
				<?php foreach ($get_tabs as $_index => $_tab): ?>
					<?php if($alias = $this->getChildHtml($_tab['alias'])): ?>
					<dt class="tab"><a href="javascrpt:void(0);" data-toggle="tab"><?php echo $_tab['title']?></a></dt>
					<dd class="tab-container">
						<div class="tab-content"><?php echo $alias; ?></div>
					</dd>
					<?php endif; ?>
				<?php endforeach;?>
			</dl>
		</div>
	</div>
</div>
<?php endif; ?>
