<?php 
	$tmpCfg = Mage::registry('tmpCfg');
	$theme=$this->helper('kasuva'); 
	$setingsCfg=$tmpCfg['set']['product_upsell'];
	if(count($this->getItemCollection()->getItems()) && $setingsCfg['upsellprod_enable']):
		$upsellCount=count($this->getItemCollection()->getItems());
		$maxprod=$setingsCfg['upsellprod_max'];
		$secTitle=$setingsCfg['upsellprod_title'];
		$size=($upsellCount>$maxprod)? $maxprod : $upsellCount;
		$slideitems=4;
		$layout=$theme->getTemplateLayout($this);
		if($layout=='1column'){
			$slideitems=$setingsCfg['upsellprod_1c_item'];
		}else if($layout=='2columns-left'){
			$slideitems=$setingsCfg['upsellprod_2c_item'];
		}else if($layout=='3columns'){
			$slideitems=$setingsCfg['upsellprod_3c_item'];
		}
		$price=$setingsCfg['upsellprod_price_enable'];
		$rating=$setingsCfg['upsellprod_rating_enable'];
		$sku=$setingsCfg['upsellprod_sku_enable'];
		$wishlist=$setingsCfg['upsellprod_wishlist_enable'];
		$quickview=$setingsCfg['upsellprod_quickview_enable'];
?>
<?php $_columnCount = $this->getColumnCount(); ?>
<section class="section upsell-section">
	<div class="row">
		<div class="col-sm-12">
			<h3 class="section-title"><?php echo $secTitle;?></h3>
			<div class="product-slider owl-center-cont">
				<div class="home-owl-carousel custom-carousel outer-top-xs" data-item="<?php echo $slideitems; ?>">
					<?php $this->resetItemsIterator() ?>
					<?php $i=1; foreach ($this->getItemCollection()->getItems() as $_link){ ?>
						<?php $htm_badge=$theme->getProductLabel($_link); ?>
						<?php $htm_badge.=($quickview)? $this->helper('ajaxpkt')->getQuickViewLink($_product)  : '' ; ?>
						<div class="item item-carousel">
							<div class="products">
								<div class="product">
									<div class="product-image">
										<div class="image">
											<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_link, 'small_image'), null, true) ?>" class="product-image">
												 <img id="product-collection-image-<?php echo $_link->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->constrainOnly(true)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(211,273); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_link, 'small_image'), null, true) ?>" width="211" height="273" />
											</a>
										</div>
										<?php echo $htm_badge; ?>
									</div>
									<div class="product-info text-left">
										<h3 class="name product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($_link->getName(), null, true) ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></h3>
										<?php if($sku): ?><p class="sku"><span class="label"><?php echo $this->__('SKU') ?>:</span><span class="value"><?php echo Mage::getModel('catalog/product')->load($_link->getId())->getSku();?></span></p><?php endif; ?>
										<?php if($rating):?>
										<?php $reviews=$this->getReviewsSummaryHtml($_link,'short') ?>
										<?php if($reviews): ?>
											<?php echo $reviews; ?>
										<?php else: ?>
										<div class="ratings">
											<div class="rating-box">&nbsp;</div>
										</div>
										<?php endif; ?>
										<?php endif; ?>
										<?php if($price): ?>
										<div class="product-price">	
											<?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
										</div>
										<?php endif; ?>
									</div>
									<?php if($wishlist): ?>
									<div class="cart clearfix animate-effect">
										<div class="action">
											<ul class="list-unstyled">
												<?php if ($this->helper('wishlist')->isAllow()) : ?>
													<li><button onclick='ajaxWishlist(this,"<?php echo $this->helper('wishlist')->getAddUrl($_link) ?>","<?php echo $_link->getId()?>");return false;' class="link-wishlist button wishlist"><i class="icon fa fa-heart"></i><span class="title"><?php echo $this->__('Add to Wishlist') ?></span></button></li>
												<?php endif; ?>
											</ul>
										</div>
									</div>
									<?php endif; ?>
								</div>
							</div>
						</div>
						<?php if($i>=$size){break;} ?>
					<?php $i++; } ?>
				</div>
			</div>
		</div>
	</div>
</section>
<?php endif; ?>