<?php $Cfg=Mage::helper('unicase/config')->getTpcfg('unicase_settings/product_info'); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php if ($this->hasOptions()=='1'){ $has_opt='pi-opt'; }else{ $has_opt=''; } ?>
<?php 
$sku=$Cfg['productinfo_sku_enable']; 
$qckinfo=$Cfg['productinfo_quickinfo_enable'];
$tabs=$Cfg['productinfo_tabs_enable'];
$tabstyle=($Cfg['product_tab_style']=='verticle') ? 'pi-ver-tabs' : 'pi-hor-tabs';
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view single-product">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
			<div class="row">
				<div class="gallery-holder">
					<div class="product-img-box">
						<?php echo $this->getChildHtml('media') ?>
					</div>
				</div>
				<div class="product-info-block">
					<div class="product-shop product-info <?php echo $has_opt; ?>">
						<div class="product-name">
							<h1 class="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
						</div>
						<div class="extra-info m-t-20">
							<ul class="pi-b1">
								<li class="review">
								<?php if($this->getReviewsSummaryHtml($_product,'short')): ?>
									<?php echo $this->getReviewsSummaryHtml($_product,false, true) ?>
								<?php else: ?>
								<div class="ratings">
									<div class="rating-box">&nbsp;</div>
									<div class="rating-links"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></div>
								</div>
							<?php endif; ?>
								</li>
								<li class="wr-review">
									<div class="rw-lnk"><a href="<?php echo Mage::getUrl('review/product/list', array('id'=> $_product->getId())); ?>#review-form" rel="nofollow"><i class="fa fa-pencil"></i>&nbsp;&nbsp;<?php echo $this->__('Write a Review') ?></a></div>
								</li>
								<?php if ($this->canEmailToFriend()): ?>
								<li class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><i class="fa fa-address-book-o"></i>&nbsp;&nbsp;<?php echo $this->__('Email to a Friend') ?></a></li>
								<?php endif; ?>
							</ul>
							<?php if($sku): ?>
							<div class="stock-container info-container m-t-15 ps-lst">
								<?php echo $this->getChildHtml('product_type_availability'); ?>
								<p class="sku"><span class="label"><?php echo $this->__('SKU'); ?>:</span><span class="value"><?php echo $_product->getSku(); ?></span></p>
							</div>
							<?php endif; ?>
						</div>
						<?php echo $this->getChildHtml('alert_urls') ?>
						<?php if ($_product->getShortDescription() && $qckinfo):?>
							<div class="short-description m-t-20">
								<div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
							</div>
						<?php endif;?>
						<div class="price-info price-container info-container m-t-20">
							<?php echo $this->getPriceHtml($_product); ?>
							<?php echo $this->getChildHtml('bundle_prices') ?>
							<?php echo $this->getTierPriceHtml() ?>
						</div>
						<?php echo $this->getChildHtml('other');?>
						<?php if ($_product->isSaleable() && $this->hasOptions()):?>
							<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
						<?php endif;?>
						<?php echo $this->getChildHtml('product_type_data') ?>
						<?php echo $this->getChildHtml('extrahint') ?>
						<?php if (!$this->hasOptions()):?>
						<div class="add-to-cart-wrapper info-container">
							<div class="add-to-box">
								<?php if($_product->isSaleable()): ?>
										<?php echo $this->getChildHtml('addtocart') ?>
								<?php endif; ?>
									<div class="pi-b2">
										<?php echo $this->getChildHtml('addto') ?>
									</div>
							<?php echo $this->getChildHtml('extra_buttons') ?>
							</div>
						</div>
						<?php elseif (!$_product->isSaleable()): ?>
								<?php echo $this->getChildHtml('addto') ?>
								<?php //echo $this->getChildHtml('sharing') ?>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</form>
		<div class="clearer"></div>
		<?php if ($_product->isSaleable() && $this->hasOptions()):?>
			<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
		<?php endif;?>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
    </div>
	<?php echo $this->getChildHtml('info_tabs') ?>
	<?php echo $this->getChildHtml('product_additional_data') ?>
	<?php echo $this->getChildHtml('related_products') ?>
    <?php echo $this->getChildHtml('upsell_products') ?>
</div>
