<?php 
$store = Mage::app()->getStore();
$code  = $store->getCode();
$enable = Mage::getStoreConfig('fltproducts/lastordered/active',$code);
?>
<?php if($enable == 1) { ?>
	<?php 
	$column_count =(Mage::getStoreConfig('fltproducts/lastordered/column_count',$code)) ? Mage::getStoreConfig('fltproducts/lastordered/column_count',$code) : 4;
	$styles=(Mage::getStoreConfig('fltproducts/lastordered/products_styles',$code)) ? Mage::getStoreConfig('fltproducts/lastordered/products_styles',$code) : 'slider';
	$row_count=(Mage::getStoreConfig('fltproducts/lastordered/row_count',$code)) ? Mage::getStoreConfig('fltproducts/lastordered/row_count',$code) : '2';
	?>
	<section class="section lastordered-product wow fadeInUp">
		<h3 class="section-title"><?php echo Mage::getStoreConfig('fltproducts/lastordered/title',$code); ?></h3>
	<?php echo $this->getLayout()->createBlock('fltproducts/lastordered_home_list')->setData(array('column_count'=>$column_count,'row_count'=>$row_count))->setTemplate('perfectus/fltproducts/'.$styles.'.phtml')->toHtml(); ?>
	</section>
<?php }  ?>