<?php 
$store = Mage::app()->getStore();
$code  = $store->getCode();
$enable = Mage::getStoreConfig('fltproducts/newprodcattabs/active',$code);
?>
<?php if($enable == 1) { ?>
<div id="product-tabs-slider" class="scroll-tabs outer-top-xs wow fadeInUp">
<?php echo $this->getLayout()->createBlock('fltproducts/newproduct_home_list')->setTemplate('perfectus/fltproducts/tab_slider_list.phtml')->toHtml(); ?>
</div>
<?php }  ?>


