<?php
	$tmpCfg = Mage::registry('tmpCfg');
	$theme=$this->helper('unicase');
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
	//$slideitems=($this->getData("column_count"))? $this->getData("column_count") : 6;
	$setingsCfg=$tmpCfg['set']['products_slider'];
	$CfgDesign=$tmpCfg['deg'];
	$_imgWidth=($setingsCfg['prodsliderimg_width'])? $setingsCfg['prodsliderimg_width'] : 276;
	$_imgHeight=($setingsCfg['prodsliderimg_height']) ? $setingsCfg['prodsliderimg_height'] : 342;
	$sku=$setingsCfg['prodslider_sku_enable'];
	$rating=$setingsCfg['prodslider_rating_enable'];
	$wishlist=$setingsCfg['prodslider_wishlist_enable'];
	$compare=$setingsCfg['prodslider_compare_enable'];
	$addtocart=$setingsCfg['prodslider_addtocart_enable'];
	$price=$setingsCfg['prodslider_price_enable'];
	$quickview=$setingsCfg['prodslider_quickview_enable'];
	if($setingsCfg['prodslider_aspratio']){
		$_imgHeight=0;
	}
	$altImg=$setingsCfg['prodslider_altimg_enable'];
	$AjakpktCfg=Mage::helper('unicase/config')->getTpcfg('ajaxpkt/ajaxpkt_conf/ajaxpkt_active');
	
	$store = Mage::app()->getStore();
	$code  = $store->getCode();
	$newproconfig = Mage::getStoreConfig('fltproducts/newprodcattabs',$code);
	$cats=Mage::helper('fltproducts')->getNewProdsCategories($_productCollection,$newproconfig['max_cat']);
	$slideitems=4;
	$getData = $this->getData();
	if($getData["slider"])){
		$slideitems=$getData["slider"];
	}else if($newproconfig['slider']){
		$slideitems=$newproconfig['slider'];
	}
	
	$blank_gif = $this->getSkinUrl('images/blank.gif');
	$mage_core = Mage::helper('core');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php //$_columnCount = $this->getColumnCount(); ?>
	<?php if(!empty($cats)){?>
	<div class="row">
		<div class="col-sm-12">
			<div class="more-info-tab clearfix ">
				<h3 class="new-product-title pull-left"><?php echo $this->__($newproconfig['title']); ?></h3>
				<ul class="nav nav-tabs nav-tab-line pull-right" id="new-products-tabs">
					<?php $ci=0;foreach($cats as $ck=>$cv){ ?>
					<li class="<?php echo ($ci==0)? 'active': ''; ?>"><a data-transition-type="backSlide" href="#tbnp-<?php echo $ck; ?>" data-toggle="tab"><?php echo $cv; ?></a></li>
					<?php $ci++;} ?>
				</ul>
			</div>
			<div class="tab-content outer-top-xs">
				<?php $ci=0;foreach($cats as $ck=>$cv){
					//$_productCollection->addAttributeToFilter('category_id', array('in' =>$ck));		
				?>
				<div class="tab-pane in <?php echo ($ci==0)? 'active': ''; ?>" id="tbnp-<?php echo $ck; ?>">
					<div class="product-slider owl-center-cont">
						<div class="home-owl-carousel owl-carousel outer-top-xs" data-item="<?php echo $slideitems; ?>">
							<?php $i=0; foreach ($_productCollection as $_product){ 
								if($ck==0 || in_array($ck,$_product->getCategoryIds())){
							?>
							<?php $htm_badge=$this->helper('unicase')->getProductLabel($_product); ?>
							<?php $htm_badge.=($quickview)? $this->helper('ajaxpkt')->getQuickViewLink($_product)  : '' ; ?>
								<div class="item item-carousel">
									<div class="products">
										<div class="product">
											<div class="product-image">
												<div class="image">
													<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
														 <img class="lazyOwl" id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $theme->getProdImg($_product, $_imgWidth, $_imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="<?php echo $_imgWidth; ?>" height="<?php echo $_imgHeight; ?>" />
														<?php if($altImg): ?>
														<?php echo $theme->getProdAltImg($_product,$_imgWidth,$_imgHeight,'small_image'); ?>
														<?php endif; ?>
														
													</a>
												</div>
												<?php echo $htm_badge; ?>
											</div>
											<div class="product-info text-left">
												<h3 class="name product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
												<?php if($sku): ?><p class="sku"><span class="label"><?php echo $this->__('SKU') ?>:</span><span class="value"><?php echo $_product->getSku();?></span></p><?php endif; ?>
												<?php if($rating): ?>
												<?php $reviews=$this->getReviewsSummaryHtml($_product,'short') ?>
												<?php if($reviews): ?>
													<?php echo $reviews; ?>
												<?php else: ?>
												<div class="ratings">
													<div class="rating-box">&nbsp;</div>
												</div>
												<?php endif; ?>
												<?php endif; ?>
												<?php if($price): ?>
												<div class="product-price">	
													<?php echo $this->getPriceHtml($_product, true) ?>
												</div>
												<?php endif; ?>
											</div>
											<div class="cart clearfix animate-effect">
												<div class="action">
													<ul class="list-unstyled">
														<?php if($addtocart): ?>
														 <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
															<li class="add-cart-button btn-group">
																<?php if($CfgDesign['basic']['btn_style']=='ucbtns2'){?>
																<button class="button btn-cart icon" title="<?php echo $mage_core->quoteEscape($this->__('Add to Cart')); ?>" data-toggle="dropdown" type="button"  onclick="<?php echo ($AjakpktCfg) ? "setLocationAjax(this,'".$this->getAddToCartUrl($_product)."','".$_product->getId()."')" : "setLocation('".$this->getAddToCartUrl($_product)."')"; ?>"><i class="fa fa-shopping-cart"></i></button>
																<?php } ?>
																<button type="button" title="<?php echo $mage_core->quoteEscape($this->__('Add to Cart')); ?>" class="button btn-cart" onclick="<?php echo ($AjakpktCfg) ? "setLocationAjax(this,'".$this->getAddToCartUrl($_product)."','".$_product->getId()."')" : "setLocation('".$this->getAddToCartUrl($_product)."')"; ?>"><span><?php echo $this->__('Add to Cart') ?></span></button>
															</li>
														<?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
															<li class="add-cart-button btn-group">
																<?php if($CfgDesign['basic']['btn_style']=='ucbtns2'){?>
																<button class="button btn-cart icon" title="<?php echo $mage_core->quoteEscape($this->__('Add to Cart')); ?>" onclick="<?php echo ($AjakpktCfg) ? "showOptions(this,'".$_product->getId()."')" : "setLocation('".$_product->getProductUrl()."')"; ?>"><i class="fa fa-file-text-o"></i></button>
																<?php } ?>
																<button class="button btn-cart" title="<?php echo $mage_core->quoteEscape($this->__('Add to Cart')); ?>" onclick="<?php echo ($AjakpktCfg) ? "showOptions(this,'".$_product->getId()."')" : "setLocation('".$_product->getProductUrl()."')"; ?>"><?php echo $this->__('Add to Cart'); ?></button>
																<?php if($AjakpktCfg): ?>
																<a href='<?php echo $this->getUrl('ajaxpkt/index/options',array('product_id'=>$_product->getId()));?>' class='ajaxpkt-qckview' id='ajaxpkt<?php echo $_product->getId()?>' style='display:none'><?php echo $this->__('Ajaxpkt') ?></a>
																<?php endif; ?>
															</li>
														<?php else: ?>
															<li><p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p></li>
														<?php endif; ?>
														<?php endif;?>
														<?php if(($this->helper('wishlist')->isAllow()) && $wishlist) : ?>
															<li class="lnk wishlist"><button onclick="<?php echo ($AjakpktCfg) ? "ajaxWishlist(this,'".$this->helper('wishlist')->getAddUrl($_product)."','".$_product->getId()."');return false;" : "setLocation('".$this->helper('wishlist')->getAddUrl($_product)."')"; ?>" title="<?php echo $this->__('Wishlist') ?>" class="link-wishlist button wishlist"><i class="icon fa fa-heart"></i><span class="hidden"><?php echo $this->__('Add to Wishlist') ?></span></button></li>
														<?php endif; ?>
														<?php if(($_compareUrl=$this->getAddToCompareUrl($_product)) && $compare ): ?>
															<li  class="lnk"><button onclick="<?php echo ($AjakpktCfg) ? "ajaxCompare(this,'".$_compareUrl."','".$_product->getId()."');return false;" : "setLocation('".$_compareUrl."')"; ?>" title="<?php echo $this->__('Compare') ?>" class="link-compare button compare"><i class="fa fa-retweet"></i><span class="hidden"><?php echo $this->__('Add to Compare') ?></span></button></li>
														<?php endif; ?>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							<?php
								}
							} ?>
							
						</div>
						<div class='slick-controls'><span class='slick-prev'></span><span class='slick-next'></span></div>
					</div>
				</div>
				<?php $ci++; } ?>
			</div>
		</div>
	</div>
	<?php } ?>
<?php endif; ?>