<div class="footer-subscribe mobile-collapse">
	<div class="module-heading outer-bottom-xs mobile-collapse__title">
		<h4 class="module-title"><?php echo $this->__('Newsletter') ?></h4>
	</div>
	<div class="module-body mobile-collapse__content">
		 <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-footer-validate-detail">
		<div class="form-subscribe-header">
			<span for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></span>
		</div>
		<div class="input-box">
		   <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" />
		</div>
		<div class="actions">
			<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
		</div>
		</form>
		<script type="text/javascript">
		//<![CDATA[
			var newsletterFooterSubscriberFormDetail = new VarienForm('newsletter-footer-validate-detail');
		//]]>
		</script>
	</div>
</div>