<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.18
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<div class="block block-blog block-list">
	<div class="block-title">
		<strong><span><?php echo Mage::helper('blog')->__('Recent Posts'); ?></span></strong>
	</div>
	<div class="block-content blog-page">
		<?php if ($posts = $this->getRecent()): ?>
			<div class="menu-recent">
				<ul>
					<?php foreach ($posts as $post): ?>
						<li class="postWrapper blog-post">
							<?php if($post->getImage()){ ?>
								<div class="product_img_inner">
									<div class="img_cont">
										<a href="<?php echo $post->getAddress(); ?>" ><img src="<?php echo Mage::getModel('blog/post')->resizeImg($post->getImage(),263,121); ?>" alt="<?php echo $post->getTitle(); ?>" title="<?php echo $post->getTitle(); ?>" width="263" height="121" /></a>
									</div>
								</div>
							<?php } ?>
							<div class="postTitle">
								<h1><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h1>
								<div class="etc-info">
									<span class="author">&nbsp;<?php echo $post->getUser(); ?></span>
									<span class="date-time">&nbsp;<?php echo date("d/m/Y", strtotime($post->getCreatedTime()));; ?></span>
								</div>
							</div>
							<?php $desc=strip_tags($post->getPostContent()); 
							$dots=(strlen($desc) > 70) ? '...' : '';
							?>
							<div class="postContent std"><?php echo substr($desc,0,70).$dots; ?></div>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php endif; ?>
	</div>
</div>
<?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
<div class="block block-blog-categories block-list">
	<div class="block-title">
		<strong><span><?php echo Mage::helper('blog')->__('Categories'); ?></span></strong>
	</div>
	<div class="block-content">
		<div class="menu-categories">
			<ul>
				<?php $cats = $this->getCategories(); ?>
				<?php foreach ($cats as $cat): ?>
					<li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
	<?php endif; ?>
	</div>
</div>
    <?php echo $this->getChildHtml('blog_tags'); ?>