<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.18
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper blog-page">
	<div class="single-post blog-post">
		<?php if($post->getImage()){ ?>
			<div class="product_img_inner">
				<div class="img_cont">
					<a href="<?php echo $post->getAddress(); ?>" ><img src="<?php echo Mage::getModel('blog/post')->resizeImg($post->getImage(),870,400); ?>" alt="<?php echo $post->getTitle(); ?>" title="<?php echo $post->getTitle(); ?>" height="400" width="870" /></a>
				</div>
			</div>
		<?php } ?>
		<div class="postTitle">
			<h1><?php echo $post->getTitle(); ?></h1>
			<div class="etc-info">
				<span class="author">
				<?php $postCats = $post->getCats(); ?>
				<?php if (!empty($postCats)): ?>
					<?php echo Mage::helper('blog')->__('Posted in'); ?>
					<?php foreach ($postCats as $title => $url): ?>
						<a href="<?php echo $url; ?>"><?php echo $title; ?></a>
					<?php endforeach; ?>
				<?php else: ?>
					<?php echo Mage::helper('blog')->__('Posted'); ?>
				<?php endif; ?><?php echo $this->__("By"); ?> <span class="poster"><?php echo $post->getUser(); ?></span>
				</span>
				<?php if ($this->getCommentsEnabled()): ?>
				<span class="review"><?php echo ($post->getCommentCount())? $post->getCommentCount() : '0'; ?>&nbsp;<?php echo Mage::helper('blog')->__('Comments'); ?></span>
				<?php endif; ?>
				<span class="date-time">&nbsp;<?php echo $post->getCreatedTime(); ?></span>
			</div>
		</div>

		<div class="postContent std"><?php echo $post->getPostContent(); ?></div>
		<?php echo $this->getBookmarkHtml($post) ?>
		<?php if(Mage::getStoreConfig('blog/blog/tagspost')){?>
		<div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
		<?php } ?>
	</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
<div class="commentWrapper blog-review">
	<div class="row">
		<div class="col-md-12">
			<?php $comments = $this->getComment(); ?>
			<div class="commentTitle"><a name="commentBox" ></a>
				<h3 class="title-review-comments"><?php echo $this->__('Post Comments') ?></h3>
			</div>
			<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
			<?php if(count($comments) > 0): ?>
				<?php if($comments):?>
				<div class="comment-list">
					<?php foreach ($comments as $comment) : ?>
						<div class="blog-comments">
							<div class="commentDetails">
								<h4 class="username"><?php echo $this->getClearComment($comment->getUser()); ?></h4> 
								<span class="review-action pull-right"><?php echo $this->__("posted on") ?> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></span>
							</div>
							<div class="commentContent"><?php echo nl2br($this->getClearComment($comment->getComment())); ?></div>
						</div>
					<?php endforeach; ?>
				</div>
				<?php endif; ?>
			<?php endif; ?>
			 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>


			<?php if ($post->getComments()): ?>
				<div class="postError"><?php //echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
			<?php else: ?>
				<div class="blog-write-comment m-t-20">
					<div class="row">
						<?php if ($this->getLoginRequired()): ?>
							<?php if ($this->helper('customer')->isLoggedIn()): ?>
								<form action="" id="postComment" method="post">
									<div class="fieldset">
										<div class="col-md-12">
											<h4 class="legend"><?php echo Mage::helper('blog')->__('Write Comment') ?></h4>
										</div>
										<ul class="form-list">
											<li>
												<div class="col-md-12">
													<div class="input-box aw-blog-comment-area">
														<label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
														<textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text form-control kasuva-form-control" style="height:150px;width:100%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
													</div>
												</div>
											</li>
										</ul>
									</div>
									<div class="button-set col-md-12">
										<input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
										<input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
										<input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
										<em class="required"><?php echo $this->__('* Required Fields') ?></em>
										<button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
									</div>
								</form>

								<script type="text/javascript">
									var contactForm = new VarienForm('postComment', false);
								</script>

							<?php else: ?>
								<div class="col-md-12">
									<p><?php //echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
									<p><a class="lnk-login" href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
								</div>
							<?php endif ?>

						<?php else: ?>
							<form action="" id="postComment" method="post">
								<div class="fieldset">
									<div class="col-md-12">
										<h4 class="legend"><?php echo Mage::helper('blog')->__('Write Comment') ?></h4>
									</div>
									<ul class="form-list">
										<li>
											<div class="col-md-6">
												<div class="input-box">
													<label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
													<input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry form-control kasuva-form-control text-input" type="text" />
												</div>
											</div>
											<div class="col-md-6">
												<div class="input-box">
													<label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
													<input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry form-control kasuva-form-control text-input validate-email" type="text" />
												</div>
											</div>
											<div class="col-md-12">
												<div class="input-box aw-blog-comment-area">
													<label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
													<textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text form-control kasuva-form-control" style="height:150px;width:100%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
												</div>
											</div>
										</li>
										<?php
										if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
											?><li><div class="col-md-12"><?php
												require_once 'recaptcha/recaptchalib-aw.php';

												// Get a key from http://recaptcha.net/api/getkey
												$publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
												$privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
												$error = null;

												echo recaptcha_get_html($publickey, $error, Mage::app()->getStore()->isCurrentlySecure());
															?></div></li><?php
											}
										?>
									</ul>
								</div>
								<div class="button-set col-md-12">
									<input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
									<em class="required"><?php echo $this->__('* Required Fields') ?></em>
									<button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
								</div>
							</form>

							<script type="text/javascript">
								var contactForm = new VarienForm('postComment', false);
							</script>
						<?php endif; ?>
					<?php endif; ?>
					</div>
				</div>
		</div>
	</div>
</div>
<?php endif; ?>
</div>