<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.18
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php 
$tmpCfg = Mage::registry('tmpCfg');
$CfgSettings = $tmpCfg['set'];
$prodbtn_style = ($CfgSettings['general']['product_btn_style']!='')? $CfgSettings['general']['product_btn_style'] : 'ucbs1-m';
$blog_helper = Mage::helper('blog');
?>
<?php if ($posts = $this->getRecentSlider()): ?>
    <section class="section outer-top-xs wow fadeInUp <?php echo $prodbtn_style; ?>">
		<div class="row">
			<div class="col-md-12">
			<h3 class="section-title"><?php echo $blog_helper->__('Latest Posts'); ?></h3>
			<div class="blog-slider-container owl-center-cont">
				<div class="owl-carousel blog-slider custom-carousel outer-top-xs">
					<?php foreach ($posts as $post): ?>
					<div class="item product">
						<div class="blog-post">
							<?php if($post->getImage()){ ?>
								<div class="blog-post-image">
									<div class="image">
										<a href="<?php echo $post->getAddress(); ?>" ><img src="<?php echo Mage::getModel('blog/post')->resizeImg($post->getImage(),370,170); ?>" alt="<?php echo $post->getTitle(); ?>" title="<?php echo $post->getTitle(); ?>" width="370" height="170" /></a>
									</div>
								</div>
							<?php } ?>
							<div class="blog-post-info text-left">
								<h3 class="name"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h3>	
								<span class="info"><?php echo $blog_helper->__('By'); ?><span class="author">&nbsp;<?php echo $post->getUser(); ?></span>-<span class="date-time">&nbsp;<?php echo date("d/m/Y", strtotime($post->getCreatedTime()));; ?></span><?php if ($this->getCommentsEnabled()): ?>-<span class="review"><?php echo ($post->getCommentCount())? $post->getCommentCount() : '0'; ?>&nbsp;<?php echo $blog_helper->__('Comments'); ?></span><?php endif; ?></span>
								<?php $desc=strip_tags($post->getPostContent()); 
									$dots=(strlen($desc) > 70) ? '...' : '';
								?>
								<p class="text"><?php echo substr($desc,0,70).$dots; ?></p>
								<a href="<?php echo $post->getAddress(); ?>" class="lnk button btn-primary"><?php echo $blog_helper->__('Read more'); ?></a>
							</div>
						</div>
					</div>
					<?php endforeach; ?>
				</div>
			</div>
			</div>
		</div>
    </section>
<?php endif; ?>