<?php
$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) {
    $_cartQty = 0;
}
?>
<div id="minicart-error-message" class="minicart-message"></div>
<div id="minicart-success-message" class="minicart-message"></div>
<div class="minicart-wrapper">
    <?php $_items = $this->getRecentItems(100) ?>
    <?php $countItems = count($_items); ?>
    <?php if($countItems): ?>
		<ul id="cart-sidebar" class="cart_list product_list_widget">
			<?php foreach($_items as $_item): ?>
				<?php echo $this->getItemHtml($_item) ?>
			<?php endforeach; ?>
		</ul>
        <div id="minicart-widgets">
            <?php echo $this->getChildHtml('cart_promotion') ?>
        </div>
		<p class="total">
                <?php if ($this->canApplyMsrp()): ?>
                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                    <strong><?php echo $this->__('Cart Subtotal:') ?></strong> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
        </p>
        <div class="minicart-actions buttons">
            <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                <ul class="checkout-types minicart">
                    <?php echo $this->getChildHtml('extra_actions') ?>
                    <li>
						<a class="button wc-forward" href="<?php echo $this->getUrl('checkout/cart'); ?>">
							<?php echo $this->__('View Cart'); ?>
						</a>
                        
                    </li>
                </ul>
            <?php endif ?>
            <a title="<?php echo Mage::helper('core')->quoteEscape($this->__('Checkout')) ?>" class="cart-link button checkout wc-forward" href="<?php echo $this->getCheckoutUrl() ?>">
				<?php echo $this->__('Checkout') ?>
			</a>
        </div>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <?php endif ?>
</div>
