<?php
$installer = $this;
$installer->startSetup();
$installer->addAttribute('catalog_category', 'pu_megamenu_menu_status', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Show in Menu',
		'input' => 'select',
		'backend'=> '',
		'source' => 'megamenu/category_attribute_source_block_yesno',
		'note'=> 'Display Category in Main Navigation Menu and Mobil Menu.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 9,
		'default' => '1',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_megamenu_vmenu_status', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Show in Verticle Menu',
		'input' => 'select',
		'backend'=> '',
		'source' => 'megamenu/category_attribute_source_block_yesno',
		'note'=> 'Display Category in Verticle Menu.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 9,
		'default' => '1',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_megamenu_menu_type', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Menu Type',
		'input' => 'select',
		'backend'=> '',
		'source' => 'megamenu/category_attribute_source_menutype',
		'note'=> 'Set Menu Type for Megamenu.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 10,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_cus_width', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Dropdown Custom Width',
		'input' => 'text',
		'backend'=> '',
		'note'=> 'Set Menu Width For Megamenu.Ex. 800px, Applicable only Menu Type = Custom.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 20,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_cols', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Show Columns',
		'input' => 'select',
		'backend'=> '',
		'source' => 'megamenu/category_attribute_source_columns',
		'note'=> 'Set number of columns display in Megamenu. Applicable only Top Level Sub Categories.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 30,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_label', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Category Labels',
		'input' => 'select',
		'backend'=> '',
		'source' => 'megamenu/category_attribute_source_catlabels',
		'note'=> 'Set Menu Labels.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 40,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_icon', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Icon (Font Awesome)',
		'input' => 'text',
		'backend'=> '',
		'note'=> 'Display Category Icon in Verticle Megamenu . Ex:"fa fa-blind", This fields applicable only for Top Level Categories.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 40,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_lblock_cols', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Left Block Width',
		'input' => 'select',
		'backend'=> '',
		'source' => 'megamenu/category_attribute_source_columns',
		'note'=> 'Properties of Left Block. This fields affected only Top Level SubCategories.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 50,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_lblock_content', array(
		'group'=> 'Megamenu',
		'type' => 'text',
		'label' => 'Left Block',
		'input' => 'textarea',
		'backend'=> '',
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'used_in_product_listing' => false,
		'sort_order'=> 60,
		'wysiwyg_enabled' => true,
        'visible_on_front' => true,
        'is_html_allowed_on_front' => true,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'note'=> 'This field applicable only for Top Level Categories.',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_rblock_cols', array(
		'group'=> 'Megamenu',
		'type' => 'varchar',
		'label' => 'Right Block Width',
		'input' => 'select',
		'backend'=> '',
		'source' => 'megamenu/category_attribute_source_columns',
		'note'=> 'Properties of Right Block. This fields applicable only for Top Level SubCategories.',
		'visible' => true,
		'required' => false,
		'user_defined' => false,
		'visible_on_front' => true,
		'used_in_product_listing' => false,
		'is_html_allowed_on_front' => true,
		'sort_order'=> 70,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_rblock_content', array(
		'group'=> 'Megamenu',
		'type' => 'text',
		'label' => 'Right Block',
		'input' => 'textarea',
		'backend'=> '',
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'used_in_product_listing' => false,
		'sort_order'=> 80,
		'wysiwyg_enabled' => true,
        'visible_on_front' => true,
        'is_html_allowed_on_front' => true,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'note'=> 'This field applicable only for Top Level Categories.',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_tblock_content', array(
		'group'=> 'Megamenu',
		'type' => 'text',
		'label' => 'Top Block',
		'input' => 'textarea',
		'backend'=> '',
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'used_in_product_listing' => false,
		'sort_order'=> 90,
		'wysiwyg_enabled' => true,
        'visible_on_front' => true,
        'is_html_allowed_on_front' => true,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'note'=> 'This field applicable only for Top Level Categories.',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_category', 'pu_mg_bblock_content', array(
		'group'=> 'Megamenu',
		'type' => 'text',
		'label' => 'Bottom Block',
		'input' => 'textarea',
		'backend'=> '',
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'used_in_product_listing' => false,
		'sort_order'=> 100,
		'wysiwyg_enabled' => true,
        'visible_on_front' => true,
        'is_html_allowed_on_front' => true,
		'default' => '',
        'searchable'=> false,
        'filterable'=> false,
        'comparable'=> false,
        'unique'=> false,
        'position'=> 1,
		'note'=> 'This field applicable only for Top Level Categories.',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->updateAttribute('catalog_category', 'pu_mg_lblock_content', 'is_wysiwyg_enabled', 1);
$installer->updateAttribute('catalog_category', 'pu_mg_rblock_content', 'is_wysiwyg_enabled', 1);
$installer->updateAttribute('catalog_category', 'pu_mg_tblock_content', 'is_wysiwyg_enabled', 1);
$installer->updateAttribute('catalog_category', 'pu_mg_bblock_content', 'is_wysiwyg_enabled', 1);
$installer->endSetup();

if (Mage::getModel('admin/block')) {
    $installer = $this;
    $installer->startSetup();
    $connection = $installer->getConnection();
	$resource = Mage::getSingleton('core/resource');
	$block_install_ar = array();
	$block_ar = array('megamenu/sidebarnav');
	$rows = $connection->fetchAll('select * from '. $resource->getTableName('permission_block'));
	foreach ($rows as $k => $v) {
		if(in_array($v['block_name'], $block_ar)){
			unset($block_ar[array_search($v['block_name'], $block_ar)]);
		}
	}
	foreach($block_ar as $k => $v){
		$block_install_ar[] = array('block_name' => $v, 'is_allowed' => 1);
	}
		
	if(!empty($block_install_ar)){
		$installer->getConnection()->insertMultiple(
        $installer->getTable('admin/permission_block'), $block_install_ar);
		$installer->endSetup();
	}
}